services:
    backend:
        build: ./server
        container_name: backend
        restart: always
        command: sh -c "npm install && npm run dev"
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./client/dist:/usr/share/nginx/html
        depends_on:
            - backend

volumes:
    mysql_data:
