name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: SSH & Deploy to EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  password: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd ~/whatapps
                      git pull origin main
                      docker compose down
                      docker compose build
                      docker compose up -d
